server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/itsdf07
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver