server:
  port: 8080
  servlet:
    context-path: /itsdf07

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/itsdf07?useUnicode=true&characterEncoding=utf-8
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
#    thymeleaf:
#      prefix: classpath:/templates/  #配置模板引擎:是让controller层到templates文件夹寻找xx.html(src/main/resources/templates)


mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.aso.itsdf07.entity  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 配置控制台打印sql查询语句并附带查询结果数据

logging:
  level:
#    root: info
    com.aso.itsdf07.controller: debug  # 配置控制台打印指定目录下类的Logger等级